### ISSUE TITLE
Discussion of the lifetime

### ISSUE THREAD

**Issue by Cupnfish** [rgripper/village-sim#3]
https://github.com/rgripper/village-sim/blob/4211332ec83cc53eecfffc090c9c4ed65416da96/game_plugin/src/world_gen.rs#L121

I don’t know why insert is needed here. Can’t insert be moved inside the function? Is it for code reuse?

**Comment by rgripper** [comment]
Yes, the function is meant to be a helper to spawn parent-child group of sprites (to correctly align the shadow sprite, as a shadow will be used for most game entities). Inserts are not a part of this logic and are custom to every game entity.

**Comment by Cupnfish** [comment]
#4
